spring:
  #thymeleaf配置
  thymeleaf:
    cache: false #不需要thymeleaf的缓存

  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql-connector为8.0版本，兼容mysql5.7
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接池名
      pool_name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间，默认为600000（10分钟）
      idle-timeout: 1800000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认为1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis配置
  redis:
    #服务器地址
    host: 47.95.39.132
    #密码
    password: 123456
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认为8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认为8
        max-idle: 200
        #最小空闲连接，默认为0
        min-idle: 5


#mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.cyq.myseckill.pojo

#mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包
logging:
  level:
    com.cyq.seckill.mapper: debug


















